/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.taskmanagement;

import java.awt.Color;
import com.mycompany.taskmanagement.ForgetPassword;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rahul
 */
public class LogIn extends javax.swing.JDialog {

    /**
     * Creates new form LogIn
     */
    public LogIn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void logInfo(String str){
        usernameTextField.setText(str);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        LogInBtn = new javax.swing.JButton();
        SignInBtn = new javax.swing.JButton();
        forgetPasswoedBtn = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        usernameTextField.setName("usernametextField"); // NOI18N
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        LogInBtn.setText("Log In");
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogInBtnMousePressed(evt);
            }
        });
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });

        SignInBtn.setText("Sign Up");
        SignInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignInBtnMousePressed(evt);
            }
        });
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });

        forgetPasswoedBtn.setForeground(new java.awt.Color(0, 0, 204));
        forgetPasswoedBtn.setText("Forgot Password");
        forgetPasswoedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswoedBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetPasswoedBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetPasswoedBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgetPasswoedBtnMousePressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LogInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(SignInBtn)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgetPasswoedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgetPasswoedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignInBtn)
                    .addComponent(LogInBtn))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtnActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void forgetPasswoedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswoedBtnMouseClicked

       
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetPasswoedBtnMouseClicked

    private void forgetPasswoedBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswoedBtnMouseEntered
        forgetPasswoedBtn.setText("<HTML><U>Forget Password</U><HTML>");
                // TODO add your handling code here:
;
    }//GEN-LAST:event_forgetPasswoedBtnMouseEntered

    private void forgetPasswoedBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswoedBtnMouseExited
        // TODO add your handling code here:
                forgetPasswoedBtn.setText("Forget Password");

    }//GEN-LAST:event_forgetPasswoedBtnMouseExited

    private void SignInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInBtnMouseClicked
    

        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtnMouseClicked

    private void LogInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseClicked

        
       
       
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtnMouseClicked

    private void LogInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMousePressed
        // TODO add your handling code here:
         String user=usernameTextField.getText();
        String pass=jPasswordField1.getText();
        try {
             String query = "SELECT * FROM SignUp WHERE UserName = ? and Password = ?";
             String query1 = "SELECT * FROM SignUp WHERE UserName = ?";

        Connection con = DatabaseConnection.getCon();
        PreparedStatement st = con.prepareStatement(query);
        PreparedStatement st1=con.prepareStatement(query1);
        st1.setString(1, user);
        
        st.setString(1, user);
        st.setString(2, pass);

        // Execute the query to check for existing records
        ResultSet rs = st.executeQuery();
        ResultSet re1=st1.executeQuery();

        // If there are any matching records, the account already exists
        if (rs.next()) {
            // Show a pop-up message indicating that the account already exists
            Icon img=new ImageIcon("igd.png");
            JOptionPane.showMessageDialog(null, "Welcome", "Success", JOptionPane.INFORMATION_MESSAGE,img);
            setVisible(false);
            TaskList taskList=new TaskList();
            taskList.setVisible(true);
            taskList.user(user);
            taskList.DisplayTable();
            
         st.close();
        con.close();
        }

        else if(re1.next()) {
            jLabel3.setText("Enter the Correct Password");
            st.close();
        con.close();

        } 
        else{
            jLabel3.setText("Enter the correct Username and Password");
        }
            st.close();
        con.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error", "Error", JOptionPane.ERROR_MESSAGE);

    
        }
        
    }//GEN-LAST:event_LogInBtnMousePressed

    private void SignInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInBtnMousePressed
        // TODO add your handling code here:
            setVisible(false);
        SignUp signUp=new SignUp();
        signUp.setVisible(true);
    }//GEN-LAST:event_SignInBtnMousePressed

    private void forgetPasswoedBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswoedBtnMousePressed
        // TODO add your handling code here:
         
        setVisible(false);
        ForgetPassword fp=new ForgetPassword( null, rootPaneCheckingEnabled);
        fp.logInfo(usernameTextField.getText());
        fp.setVisible(true);
    }//GEN-LAST:event_forgetPasswoedBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogIn dialog = new LogIn(new javax.swing.JFrame(), true);
                dialog.getContentPane().setBackground(Color.WHITE);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel forgetPasswoedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
